# .travis.yml
language: go

# You don't need to test on very old versions of the Go compiler.
# It's the user's responsibility to keep their compiler up to date.
go:
  - 1.12.x

#services:
#  - docker

# still want vendor packages
env:
  - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

before_install:
  - go get github.com/mattn/goveralls

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install golang.org/x/tools/cmd/cover

script:
  - golangci-lint run
  - $HOME/gopath/bin/goveralls -v -service=travis-ci

#after_success:
#  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
#  - mkdir -p dist
#  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o ./dist/gomotics
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#  - export REPO=$DOCKER_USER/gomotics
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
#  - echo $REPO:$TAG
#  - docker build -f Dockerfile -t $REPO:$TAG .
#  - docker push $REPO