AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple serverless project to convert transmit SOAP messages in a RESTful manner
Resources:
  restless:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: restless
      CodeUri: .
      Timeout: 30